### ISSUE TITLE
docs: readme: ormconfig sample file has incorrect output dir. It should be "egg-party-api" instead of "dist"

### ISSUE THREAD

**Issue by desertviper** [cakekindel/egg-party#27]
```javascript
        "entities": [
            "dist/db/entities/*.entity.js"
        ],
        "migrations": [
            "dist/db/migrations/*.js"
        ],
```

**Comment by cakekindel** [comment]
oh shit thank you! if you wanted, this or the other story would be a good first contribution opportunity?

**Comment by desertviper** [comment]
This is no longer an issue due to the recent changes that were done to refactor where the `function.json` file lives.  It now lives under the `egg-party-api` folder.  `dist` is now the actual distribution folder now.
