### ISSUE TITLE
build: refactor dependencies

### ISSUE THREAD

**Issue by cakekindel** [cakekindel/egg-party#43]
Speed up builds by skipping development cli tools such as ngrok

- Make CLI tool dependencies optional
- Update dockerfile to install with --no-optional
- Update Azure DevOps CI build to use --no-optional

**Comment by cakekindel** [comment]
```jsonc
{
    // ...
    "dependencies": {
        "@azure/functions": "^1.0.3", // remove
        "@nestjs/azure-func-http": "^0.1.2", // remove
        "@nestjs/common": "^6.8.4", // keep
        "@nestjs/core": "^6.8.4", // keep
        "@nestjs/microservices": "^6.8.4", // keep
        "@nestjs/platform-express": "^6.8.4", // keep
        "@nestjs/websockets": "^6.8.4", // keep
        "@types/sinon": "^7.5.0", // dev
        "@wufe/mapper": "^0.5.0", // remove
        "automapper-ts": "^1.9.0", // remove
        "axios": "^0.19.0", // keep
        "copyfiles": "^2.1.1", // remove
        "hash.js": "^1.1.7", // remove
        "moment": "^2.24.0", // try to remove
        "morphism": "^1.12.1", // try to remove
        "mssql": "^5.1.0", // keep
        "qs": "^6.9.0", // Try to remove?
        "reflect-metadata": "^0.1.13", // try to remove
        "rimraf": "^2.7.1", // optional
        "rxjs": "^6.5.3", // remove
        "sinon": "^7.5.0", // dev
        "typeorm": "^0.2.20" // keep
    },
    "devDependencies": {
        "@fluffy-spoon/substitute": "^1.89.0", // keep
        "@nestjs/testing": "^6.8.4", // keep
        "@types/axios": "^0.14.0", // remove
        "@types/chai": "^4.2.4", // keep
        "@types/express": "4.16.1", // try to remove
        "@types/mocha": "^5.2.7", // try to remove
        "@types/node": "11.13.4", // keep
        "@types/qs": "^6.5.3", // remove
        "@types/supertest": "2.0.7", // remove
        "chai": "^4.2.0", // keep
        "concurrently": "^5.0.0", // optional
        "dotenv": "^8.2.0", // move to dependencies
        "jest": "24.7.1", // remove
        "mocha": "^6.2.2", // keep
        "mocha-junit-reporter": "^1.23.1", // keep
        "mocha-typescript": "^1.1.17", // optional
        "ngrok": "^3.2.5", // optional
        "prettier": "1.17.0", // remove
        "remove": "^0.1.5", // remove (ha)
        "supertest": "4.0.2", // remove
        "ts-loader": "^6.2.1", // remove
        "ts-node": "8.1.0", // remove
        "tsc-watch": "2.2.1", // remove
        "tsconfig-paths": "3.8.0", // remove
        "tslint": "5.16.0", // keep
        "typescript": "^3.7.2", // keep
        "wait-on": "^3.3.0", // optional
        "webpack": "^4.41.2", // optional
        "webpack-cli": "^3.3.9", // optional
        "webpack-node-externals": "^1.7.2" // optional
    }
}
```

**Comment by cakekindel** [comment]
Hey @desertviper are you actively working on this? if so, could you pin all the versions (remove ^'s and ~'s)? That way the Greenkeeper integration will automatically open a PR every time one of our deps gets updated

**Comment by desertviper** [comment]
Sorry, @cakekindel ... finally getting around to trying to make some progress on this.  I'm doing some research on Greenkeeper to try and get to know it better.  Are you sure we want to remove all ^'s and ~'s?  It feels like we could quickly end up with quite a backlog of pull requests piling up.

**Comment by cakekindel** [comment]
You're totally right - that's actually super undesired. After reading their docs the overall greenkeeper workflow is this:
- if it's in range (patch for ^, minor for ~):
  - the build succeeds, then we know updating is safe and greenkeeper deletes its branch
  - the build fails, greenkeeper opens an issue saying "hey! this version is in range and breaks the build!"
- if it's out of range (e.g. a major bump)
  - greenkeeper opens a PR

so if we use ~ for all our packages we'll get PRs for major versions, if we use ^ then we'll get PRs for minor versions, if we pin all of our versions we'll get PRs for all updates. What do you think sounds the best?

**Comment by cakekindel** [comment]
I'm thinking ~ for non-critical dependencies makes sense, and ^ for important stuff like NestJS and TypeORM

**Comment by cakekindel** [comment]
also apparently you can configure the greenkeeper PR messages which would make merging them just a little easier:
```jsonc
// package.json
{
    // ...
    "greenkeeper": {
        "prTitles": {
            "basicPR": "build: update ${dependency}"
        }
    }
}

```

**Comment by desertviper** [comment]
Still a work in progress, but I've pushed the most obvious changes to the `refactor-dependencies` branch.

**Next steps:**
1. Experiment with the concept of optional dependencies by creating an `optionalDependencies` section
2. Spot check by running some manual tests to make sure things are kosher (automated tests appear to be passing).
3. Address the other concerns around docker and Azure DevOps CI

**Comment by desertviper** [comment]
Hmm... 🤔 

Racking my brains here with the `optionalDependency` thing.  I've experimented with moving some devDependencies such as `rimraf` and `ngrok` into that section.  The odd thing is... no matter whether I run...

- `npm ci --no-optional` or
- `npm i --no-optional`

... those dependencies are still there.  `rimraf` still runs fine and `ngrok` still runs.

I even went as far as removing `ngrok` altogether as a dependency, but it still runs!  Blowing away `node_modules` doesn't matter.

I must be missing something... will have to continue working on this with a fresh perspective.

**Comment by cakekindel** [comment]
are ngrok and rimraf installed globally?

**Comment by desertviper** [comment]
Ok, I've been procrastinating on completing this thing for too long.

I think I see what's going on...

1. Regarding `ngrok`.  Yes, I seem to have downloaded and installed that manually back in October of 2019 for some reason (I don't recall why).
2. Regarding `rimraf`.  It looks like there is a library called `gts` which depends on `rimraf`, which I'm guessing is why it shows up even if I remove it all together from the `package.json`.

`ngrok` doesn't have anything that depends on it, so that seems to work as an "optional dependency".

Regarding the libraries marked "try to remove".  It looks like most of those have code that are dependent on them.  I'm going to submit a pull request for what I have and we can go from there.
